package model;

import java.io.FileOutputStream;
import java.util.Date;
import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;


public class createpdf {
    public String id_pinjam;
    private String FILE = "D:\\GitHub\\Laboratory-Management-System\\src\\invoice\\invoice";
    private static Font catFont = new Font(Font.FontFamily.HELVETICA, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 24,
            Font.BOLD, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);
    
    public createpdf(String id_pinjam,String nama_member,String id_barang,String nama_barang,
            String id_lab,String nama_lab,String lama,String tgl){
        this.id_pinjam=id_pinjam;

           
        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(FILE+this.id_pinjam +".pdf"));
            document.open();
            addMetaData(document);
            addTitlePage(document,id_pinjam,nama_member,id_barang,nama_barang,id_lab,nama_lab,lama,tgl);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public String namafile(){
        return "invoice"+id_pinjam+".pdf";
    }
    private static void addMetaData(Document document) {
        document.addTitle("INVOICE BORROWING");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("LABORATORY_MANAGEMENT_SYSTEM");
        document.addCreator("LABORATORY_MANAGEMENT_SYSTEM");
    }

    private static void addTitlePage(Document document,String id_pin,String nama_member,String id_barang,
            String nama_barang,String id_lab,String nama_lab,String lama,String tgl) 
            throws DocumentException {
        Paragraph preface1 = new Paragraph();
        
        preface1.add(new Paragraph("\n                                    INVOICE", redFont));
        preface1.setAlignment(Element.ALIGN_CENTER);
        addEmptyLine(preface1, 4);
        document.add(preface1);
        // Will create: Report generated by: _name, _date
        //
        Paragraph preface3 = new Paragraph();
        preface3.add(new Paragraph("ID Peminjaman Anda : "+id_pin, subFont));
        addEmptyLine(preface3, 1);
        document.add(preface3);

        Paragraph preface4=new Paragraph();
        preface4.add(new Paragraph("Nama Member : "+nama_member+"\n",smallBold));
        addEmptyLine(preface4, 1);
        document.add(preface4);
        //
         PdfPTable table = new PdfPTable(6);
	  table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
	  table.addCell("Id Barang");
          table.addCell("Nama Barang");
          table.addCell("Id Laboran");
          table.addCell("Nama Laboran");
          table.addCell("Lama Pinjam");
          table.addCell("Tgl Pinjam");
	  table.setHeaderRows(1);
	  PdfPCell[] cells = table.getRow(0).getCells(); 
	  for (int j=0;j<cells.length;j++){
	     cells[j].setBackgroundColor(BaseColor.GRAY);
	  }
          table.addCell(id_barang);
          table.addCell(nama_barang);
          table.addCell(id_lab);
          table.addCell(nama_lab);
          table.addCell(lama);
          table.addCell(tgl);          
        document.add(table);

        Paragraph preface2 = new Paragraph();
        addEmptyLine(preface2, 20);
        preface2.add(new Paragraph("Report generated by: \n" + "LABORATORY MANAGEMENT SYSTEM" + ", \n" + new Date(),smallBold));
        document.add(preface2);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}

