package view;

import java.awt.event.ActionEvent;

public class Beranda extends javax.swing.JFrame {

    /**
     * Creates new form Beranda
     */
    char siapa='l';
    String siapah;
    public Beranda(){
        initComponents();
    }
    public Beranda(char siapa,String siapah) {
        //siapa adalah variabel untuk mengetahui yang login itu member atau laboran
        //'l' untuk laboran dan 'm' untuk member
        //siapah adalah variabel untuk mengambil username dari Masuk.java
        initComponents();
        this.siapa=siapa;
        this.siapah=siapah;
        if(siapa=='m'){
            labelnewstock.setVisible(false);
            labelcreatemember.setVisible(false);
            labelcreateadmin.setVisible(false);
            labeldetailadmin.setVisible(false);
            labelnewstock.setVisible(false);
            labeldetailmember.setText("Account Detail");
        }
        labelusername.setText(siapah);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonlogout = new javax.swing.JButton();
        labelwelcome = new javax.swing.JLabel();
        labelusername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonborrow = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonaccount = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButtonstock = new javax.swing.JButton();
        jPanelborrow = new javax.swing.JPanel();
        labelborrowingform = new javax.swing.JLabel();
        labelhistory = new javax.swing.JLabel();
        labelreturnform = new javax.swing.JLabel();
        jPanelstock = new javax.swing.JPanel();
        labelnewstock = new javax.swing.JLabel();
        labeldetailstock = new javax.swing.JLabel();
        jPanelaccount = new javax.swing.JPanel();
        labelcreateadmin = new javax.swing.JLabel();
        labeldetailadmin = new javax.swing.JLabel();
        labelcreatemember = new javax.swing.JLabel();
        labeldetailmember = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(228, 241, 254));

        jButtonlogout.setBackground(new java.awt.Color(255, 255, 255));
        jButtonlogout.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonlogout.setText("(Logout)");
        jButtonlogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButtonlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonlogoutMouseClicked(evt);
            }
        });

        labelwelcome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelwelcome.setText("Welcome ,");

        labelusername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelusername.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(labelwelcome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelusername)
                .addGap(18, 18, 18)
                .addComponent(jButtonlogout)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelwelcome)
                    .addComponent(jButtonlogout)
                    .addComponent(labelusername))
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(92, 151, 191));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(92, 151, 191));

        jButtonborrow.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonborrow.setText("Borrowing Manager");
        jButtonborrow.setBorder(null);
        jButtonborrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonborrowMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/attach.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonborrow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonborrow, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(80, 30, 150, 239);

        jPanel4.setBackground(new java.awt.Color(92, 151, 191));

        jButtonaccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonaccount.setText("Account");
        jButtonaccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonaccountMouseClicked(evt);
            }
        });
        jButtonaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaccountActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stock_contact_list.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jButtonaccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonaccount)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(570, 70, 130, 190);

        jPanel5.setBackground(new java.awt.Color(92, 151, 191));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/stockd.png"))); // NOI18N

        jButtonstock.setBackground(new java.awt.Color(255, 255, 255));
        jButtonstock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonstock.setText("Stock");
        jButtonstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonstockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonstock, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonstock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(330, 50, 130, 230);

        jPanelborrow.setBackground(new java.awt.Color(92, 151, 191));

        labelborrowingform.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelborrowingform.setText("Borrowing Form");
        labelborrowingform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelborrowingformMouseClicked(evt);
            }
        });

        labelhistory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelhistory.setText("History");
        labelhistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelhistoryMouseClicked(evt);
            }
        });

        labelreturnform.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelreturnform.setText("Returning Form");
        labelreturnform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelreturnformMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelborrowLayout = new javax.swing.GroupLayout(jPanelborrow);
        jPanelborrow.setLayout(jPanelborrowLayout);
        jPanelborrowLayout.setHorizontalGroup(
            jPanelborrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelborrowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelborrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelborrowingform, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(labelhistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelreturnform, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelborrowLayout.setVerticalGroup(
            jPanelborrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelborrowLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelborrowingform)
                .addGap(18, 18, 18)
                .addComponent(labelhistory)
                .addGap(18, 18, 18)
                .addComponent(labelreturnform, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelborrow);
        jPanelborrow.setBounds(140, 260, 130, 20);

        jPanelstock.setBackground(new java.awt.Color(92, 151, 191));

        labelnewstock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelnewstock.setText("New Stock");
        labelnewstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelnewstockMouseClicked(evt);
            }
        });

        labeldetailstock.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeldetailstock.setText("Detail Stock");
        labeldetailstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeldetailstockMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelstockLayout = new javax.swing.GroupLayout(jPanelstock);
        jPanelstock.setLayout(jPanelstockLayout);
        jPanelstockLayout.setHorizontalGroup(
            jPanelstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeldetailstock, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .addComponent(labelnewstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelstockLayout.setVerticalGroup(
            jPanelstockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelstockLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labeldetailstock)
                .addGap(18, 18, 18)
                .addComponent(labelnewstock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelstock);
        jPanelstock.setBounds(390, 260, 120, 20);

        jPanelaccount.setBackground(new java.awt.Color(92, 151, 191));

        labelcreateadmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcreateadmin.setText("Create Admin");
        labelcreateadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcreateadminMouseClicked(evt);
            }
        });

        labeldetailadmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeldetailadmin.setText("Detail Admin");
        labeldetailadmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeldetailadminMouseClicked(evt);
            }
        });

        labelcreatemember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelcreatemember.setText("Create Member");
        labelcreatemember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelcreatememberMouseClicked(evt);
            }
        });

        labeldetailmember.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labeldetailmember.setText("Detail Member");
        labeldetailmember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labeldetailmemberMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelaccountLayout = new javax.swing.GroupLayout(jPanelaccount);
        jPanelaccount.setLayout(jPanelaccountLayout);
        jPanelaccountLayout.setHorizontalGroup(
            jPanelaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeldetailadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelcreateadmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelaccountLayout.createSequentialGroup()
                .addGroup(jPanelaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labeldetailmember, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(labelcreatemember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelaccountLayout.setVerticalGroup(
            jPanelaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelaccountLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(labeldetailmember)
                .addGap(18, 18, 18)
                .addComponent(labeldetailadmin)
                .addGap(18, 18, 18)
                .addComponent(labelcreatemember)
                .addGap(18, 18, 18)
                .addComponent(labelcreateadmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanelaccount);
        jPanelaccount.setBounds(620, 260, 118, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonaccountActionPerformed
    int countbo=0;
    private void jButtonborrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonborrowMouseClicked
        // TODO add your handling code here:
        countbo++;
        if(countbo%2==1){
             jPanelborrow.setSize(140, 270);            
        }else{
            jPanelborrow.setSize(0, 0);
        }
    }//GEN-LAST:event_jButtonborrowMouseClicked
    int countst=0;
    private void jButtonstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonstockMouseClicked
        // TODO add your handling code here:
        countst++;
        if(countst%2==1){
            jPanelstock.setSize(120, 104);
        }else{
            jPanelstock.setSize(0, 0);
        }
        
    }//GEN-LAST:event_jButtonstockMouseClicked
    int countacc=0;
    private void jButtonaccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaccountMouseClicked
        // TODO add your handling code here:
        countacc++;
        if(countacc%2==1){
            jPanelaccount.setSize(118, 260);
        }else{
            jPanelaccount.setSize(0,0);
        }
        
    }//GEN-LAST:event_jButtonaccountMouseClicked

    private void jButtonlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonlogoutMouseClicked
        // TODO add your handling code here:
        Masuk login=new Masuk();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonlogoutMouseClicked

    private void labelborrowingformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelborrowingformMouseClicked
        // TODO add your handling code here:
        TambahPeminjam bor=new TambahPeminjam();
       
        bor.setVisible(true);
    }//GEN-LAST:event_labelborrowingformMouseClicked

    private void labelhistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelhistoryMouseClicked
        // TODO add your handling code here:
        RiwayatPeminjaman bor=new RiwayatPeminjaman();
        
        bor.setVisible(true);
    }//GEN-LAST:event_labelhistoryMouseClicked

    private void labelreturnformMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelreturnformMouseClicked
        // TODO add your handling code here:
        ReturnForm bor=new ReturnForm();

        bor.setVisible(true);
    }//GEN-LAST:event_labelreturnformMouseClicked

    private void labelnewstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelnewstockMouseClicked
        // TODO add your handling code here:
        TambahBarang bor=new TambahBarang();
        
        bor.setVisible(true);
    }//GEN-LAST:event_labelnewstockMouseClicked

    private void labeldetailstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetailstockMouseClicked
        // TODO add your handling code here:
        DetailStok bor= new DetailStok();
        
        bor.setVisible(true);
    }//GEN-LAST:event_labeldetailstockMouseClicked

    private void labelcreateadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcreateadminMouseClicked
        // TODO add your handling code here:
        TambahLaboran bor=new TambahLaboran();
        
        bor.setVisible(true);
    }//GEN-LAST:event_labelcreateadminMouseClicked

    private void labeldetailadminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetailadminMouseClicked
        // TODO add your handling code here:
        DetailLaboran bor=new DetailLaboran();
        
        bor.setVisible(true);
    }//GEN-LAST:event_labeldetailadminMouseClicked

    private void labelcreatememberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelcreatememberMouseClicked
        // TODO add your handling code here:
        TambahMember bor=new TambahMember();
       
        bor.setVisible(true);
    }//GEN-LAST:event_labelcreatememberMouseClicked

    private void labeldetailmemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labeldetailmemberMouseClicked
        // TODO add your handling code here:
            DetailMember bor=new DetailMember();
            bor.setVisible(true);
    }//GEN-LAST:event_labeldetailmemberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonaccount;
    private javax.swing.JButton jButtonborrow;
    private javax.swing.JButton jButtonlogout;
    private javax.swing.JButton jButtonstock;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelaccount;
    private javax.swing.JPanel jPanelborrow;
    private javax.swing.JPanel jPanelstock;
    private javax.swing.JLabel labelborrowingform;
    private javax.swing.JLabel labelcreateadmin;
    private javax.swing.JLabel labelcreatemember;
    private javax.swing.JLabel labeldetailadmin;
    private javax.swing.JLabel labeldetailmember;
    private javax.swing.JLabel labeldetailstock;
    private javax.swing.JLabel labelhistory;
    private javax.swing.JLabel labelnewstock;
    private javax.swing.JLabel labelreturnform;
    private javax.swing.JLabel labelusername;
    private javax.swing.JLabel labelwelcome;
    // End of variables declaration//GEN-END:variables
}
