/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.Connection;
import javax.swing.JOptionPane;
import model.koneksidb;
import java.text.SimpleDateFormat;
/**
 *
 * @author USER
 */
public class TambahMember extends javax.swing.JFrame {
    koneksidb datacon = new koneksidb();
    private Connection con;
    
    /**
     * Creates new form TambahMember
     */
    public TambahMember() {
        initComponents();
        setLocationRelativeTo(null);
        jButtonupdate.setVisible(false);
    }
    public TambahMember(String username){
        initComponents();setLocationRelativeTo(null);
        isiform(username);
        usernametext.setEditable(false);
        jTextFieldregisternewmembe.setText("Account Detail");
        jButtoncreate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        usernametext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButtoncreate = new javax.swing.JButton();
        jButtoncancel = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        confirm = new javax.swing.JTextField();
        jButtonupdate = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldregisternewmembe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabelback = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(145, 180, 150));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(33, 39, 35, 17);

        nama.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.add(nama);
        nama.setBounds(185, 37, 257, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Birth Date");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(33, 95, 61, 17);

        usernametext.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.add(usernametext);
        usernametext.setBounds(185, 147, 257, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Username");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(33, 149, 61, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(36, 214, 58, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(36, 282, 120, 17);

        address.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.add(address);
        address.setBounds(185, 330, 257, 131);

        jButtoncreate.setText("Create");
        jButtoncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncreateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtoncreate);
        jButtoncreate.setBounds(185, 479, 65, 23);

        jButtoncancel.setText("Cancel");
        jButtoncancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtoncancelMouseClicked(evt);
            }
        });
        jPanel2.add(jButtoncancel);
        jButtoncancel.setBounds(369, 479, 73, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(36, 330, 48, 17);

        password.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.add(password);
        password.setBounds(185, 212, 257, 30);

        confirm.setBackground(new java.awt.Color(242, 241, 239));
        jPanel2.add(confirm);
        confirm.setBounds(185, 277, 257, 30);

        jButtonupdate.setText("Update");
        jButtonupdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonupdateMouseClicked(evt);
            }
        });
        jPanel2.add(jButtonupdate);
        jButtonupdate.setBounds(278, 479, 67, 23);

        date.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                datePropertyChange(evt);
            }
        });
        jPanel2.add(date);
        date.setBounds(185, 90, 159, 20);

        jPanel1.setBackground(new java.awt.Color(37, 116, 169));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jTextFieldregisternewmembe.setEditable(false);
        jTextFieldregisternewmembe.setBackground(new java.awt.Color(37, 116, 169));
        jTextFieldregisternewmembe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldregisternewmembe.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldregisternewmembe.setText("Register New Member");
        jTextFieldregisternewmembe.setBorder(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N

        jLabelback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/left-arrow.png"))); // NOI18N
        jLabelback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelbackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabelback, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldregisternewmembe, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabelback, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(jTextFieldregisternewmembe, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void isiform(String username){
        try
            {
                String sql="SELECT * from `member` WHERE `username`='"+username+"'";
                con = datacon.getConnection();
                java.sql.Statement stm=con.createStatement();
                java.sql.ResultSet rs=stm.executeQuery(sql);
                while(rs.next()){
                    nama.setText(rs.getString(2));
                    date.setDate(rs.getDate(3));
                    usernametext.setText(rs.getString(4));
                    password.setText(rs.getString(5));
                    confirm.setText(rs.getString(5));
                    address.setText(rs.getString(6));
                }
            }catch(Exception e)
            {
                //JOptionPane.showMessageDialog(null,"GAGAL");
            }         
    }
    private void jButtoncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncreateActionPerformed
        // TODO add your handling code here:
            
            

        try {
           //String sql = "INSERT INTO member VALUES ('','"+nama.getText()+"','"+date.getText()+"','"+username.getText()+"','"+password.getText()+"','"+address.getText()+"')";
            String sql = "INSERT INTO `member` (`id_member`, `nama_member`, `tgl_lahir`, `username`, `password`, `address`) VALUES (NULL, '"+nama.getText()+"', '"+convertUtilDateToSqlDate(date.getDate())+"', '"+usernametext.getText()+"', '"+password.getText()+"', '"+address.getText()+"')";
            con=datacon.getConnection();
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        dispose();
        new TambahMember().setVisible(true);
        
        //System.out.println(nama.getText()+date.getText()+username.getText()+password.getText()+address.getText());
       
    }//GEN-LAST:event_jButtoncreateActionPerformed

    private void jButtoncancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtoncancelMouseClicked
        // TODO add your handling code here:
       
        if(jTextFieldregisternewmembe.getText()=="Register New Member"){
            dispose();
            new TambahMember().setVisible(true);
        }else if(jTextFieldregisternewmembe.getText()=="Account Detail"){
            isiform(usernametext.getText());
        }
        
    }//GEN-LAST:event_jButtoncancelMouseClicked

    private void jLabelbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelbackMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabelbackMouseClicked

    private void jButtonupdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonupdateMouseClicked
        // TODO add your handling code here:
        try {
           //String sql = "INSERT INTO member VALUES ('','"+nama.getText()+"','"+date.getText()+"','"+username.getText()+"','"+password.getText()+"','"+address.getText()+"')";
            String sql = "UPDATE `member` (`id_member`, `nama_member`, `tgl_lahir`, `username`, `password`, `address`) VALUES (NULL, '"+nama.getText()+"', '"+date.getDate()+"', '"+usernametext.getText()+"', '"+password.getText()+"', '"+address.getText()+"')";
            con=datacon.getConnection();
            java.sql.PreparedStatement pst=con.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButtonupdateMouseClicked
public static java.sql.Date convertUtilDateToSqlDate(java.util.Date date){
    if(date != null) {
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        return sqlDate;
    }
    return null;
}
    private void datePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_datePropertyChange
    }//GEN-LAST:event_datePropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahMember().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField confirm;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButtoncancel;
    private javax.swing.JButton jButtoncreate;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelback;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldregisternewmembe;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField password;
    private javax.swing.JTextField usernametext;
    // End of variables declaration//GEN-END:variables
}
